#! /bin/bash

# check ower is root?

adb wait-for-device
echo `adb shell id` | grep "uid=0(root)"
test $? != 0 && echo "has root permission" && exit

adb shell start
adb shell rm /data/local/tmp
adb shell rm /data/local.prop
adb shell mv /data/local/tmp.bak /data/local/tmp
adb reboot
