#! /bin/bash
#make clean

#make fullota
# upload for add exec permission

# check ower is root?
adb wait-for-device
echo `adb shell id` | grep "uid=0(root)"
test $? == 0 && echo "has root permission" && exit

adb shell mv /data/local/tmp /data/local/tmp.bak
adb shell ln -s /data /data/local/tmp
adb reboot
adb wait-for-device
adb shell rm /data/local.prop > /dev/null
adb shell "echo \"ro.kernel.qemu=1\" > /data/local.prop"
adb reboot
adb wait-for-device
adb shell id
